# Site settings
title: Hammer.js
email: j.tangelder@gmail.com
description: "Add multi-touch gestures to your webpage."
baseurl: ""
url: ""

# Build settings
markdown: redcarpet
permalink: pretty
exclude: [node_modules, scripts, bower_components, jsdoc-template, assets/css/index.scss]

sass:
  sass_dir: assets/css
  style: :compressed

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
